version: '3.8'

services:
  ia-ops-minio-integrated:
    build:
      context: .
      dockerfile: Dockerfile.integrated
    container_name: ia-ops-minio-portal
    restart: unless-stopped
    ports:
      - "6540:6540"       # Dashboard principal
      - "9898:9000"       # MinIO API (mantener puerto actual)
      - "9899:9001"       # MinIO Console (mantener puerto actual)
      - "8848:8848"       # REST API (mantener puerto actual)
      - "6541:6541"       # Docs (mantener puerto actual)
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin123}
      - MINIO_ENDPOINT=localhost:9000
    networks:
      - minio-integrated
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6540/health"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 60s

networks:
  minio-integrated:
    driver: bridge
    name: ia-ops-minio-integrated
