site_name: IA-Ops MinIO Documentation
site_description: Documentación completa del sistema MinIO para IA-Ops
site_author: IA-Ops Team
site_url: https://ia-ops-minio.docs

repo_name: giovanemere/ia-ops-minio
repo_url: https://github.com/giovanemere/ia-ops-minio
edit_uri: edit/main/docs_site/docs/

docs_dir: docs_site/docs
site_dir: docs_site/site

theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search:
      lang: es
  - git-revision-date-localized:
      type: date

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Inicio: index.md
  - Guía de Inicio:
    - Instalación: getting-started/installation.md
    - Configuración: getting-started/configuration.md
    - Primer Uso: getting-started/first-use.md
  - MinIO:
    - ¿Qué es MinIO?: minio/what-is-minio.md
    - Arquitectura: minio/architecture.md
    - Buckets y Objetos: minio/buckets-objects.md
    - Políticas de Acceso: minio/access-policies.md
  - API REST:
    - Introducción: api/introduction.md
    - Endpoints: api/endpoints.md
    - Ejemplos: api/examples.md
  - Despliegue:
    - Docker: deployment/docker.md
    - Producción: deployment/production.md
    - Monitoreo: deployment/monitoring.md
  - Scripts:
    - Comandos: scripts/commands.md
    - Automatización: scripts/automation.md
  - Referencia:
    - Variables de Entorno: reference/environment.md
    - Troubleshooting: reference/troubleshooting.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/giovanemere/ia-ops-minio
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/repositories/edissonz8809

copyright: Copyright &copy; 2025 IA-Ops Team
