name: Deploy IA-Ops MinIO Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs_site/**'
      - 'mkdocs.yml'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install MkDocs dependencies
        run: |
          pip install --upgrade pip
          pip install mkdocs==1.5.3
          pip install mkdocs-material==9.4.6
          pip install pymdown-extensions==10.3.1

      - name: Build documentation
        run: |
          mkdocs build --clean --strict --verbose

      - name: List generated files (debug)
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Looking for site directory:"
          find . -name "site" -type d
          echo "Contents of docs_site:"
          ls -la docs_site/ || echo "docs_site not found"

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './docs_site/site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
